### ISSUE TITLE
Update npm page for proper import statement

### ISSUE THREAD

**Issue by michalzubkowicz** [ericgio/react-bootstrap-typeahead#120]
It should be
import {Typeahead} from 'react-bootstrap-typeahead';
not
import Typeahead from 'react-bootstrap-typeahead';

**Comment by ericgio** [comment]
Fixed in `v1.0.0-beta4`

**Comment by mvolkmann** [comment]
You closed this issue but the main page still says this:
````
import Typeahead from 'react-bootstrap-typeahead';
````
It's still missing the braces.

**Comment by ericgio** [comment]
The NPM page has the updated documentation, per the title of the task. The README on Github has both: documentation for the latest stable version as well as a section describing the 1.0 beta.

**Comment by mvolkmann** [comment]
Thanks Eric!
