### ISSUE TITLE
Clicking on highlighted text in menu doesn't select the item

### ISSUE THREAD

**Issue by tomislavhren** [ericgio/react-bootstrap-typeahead#219]
### Version
2.0.0.alpha-3

### Steps to reproduce
When attribute allowNew is set to true, and when typing new selection, if you click on highlighted text, click does not work

### Expected Behavior
It should trigger selection where ever you click on link with new selection

**Comment by ericgio** [comment]
Thanks. Got a similar report a few days ago but couldn't repro. I now realize you need to click the highlighted text

**Comment by jasonmullins** [comment]
For me - clicking on any of the text (span wrapper) doesn't work, but clicking outside of the text does.

**Comment by ericgio** [comment]
@jasonmullins: Yeah you're right, I'm seeing that behavior on second look.

**Comment by alexgurr** [comment]
Yeah, can confirm I'm seeing this issue too.

**Comment by alexgurr** [comment]
I don't know about anyone else, but this happens for me without the 'allowNew' flag. It's just clicking on any of the menu options text in general that doesn't work.

**Comment by ericgio** [comment]
@alexgurr: That's correct.

I've been trying to fix this, but I'm not clear on why it's happening. The problem originally surfaced as a result of [this commit](https://github.com/ericgio/react-bootstrap-typeahead/commit/d9e9b8d83a0cfc92a353992bac8cb04338fa3105). It appears that when the text is highlighted, the click doesn't bubble up to the anchor for some reason. There also seems to be some conflict with the input `blur` and `focus` events. The solution may be to listen to the `mousedown` event rather than `click`, which should also address #224.

**Comment by alexgurr** [comment]
@ericgio happens for me even when the text isn't highlighted. Happens in every state.

**Comment by ericgio** [comment]
@alexgurr: I don't repro that, at least on Chrome. When no text is entered, it works fine. It's only when there's at least one highlighted character that it stops working. There's also no issue when using `renderMenu` or `renderMenuItemChildren`. The issue seems potentially related to the `react-highlighter` lib but I don't see anything in that code that would cause an issue.

**Comment by alexgurr** [comment]
@ericgio maybe I'm misunderstanding what you mean by highlighted text. I can reproduce this when I type something into the input, and get results in my AsyncTypeAHead menu. Can't click any of the text options in the menu. Is this what we're referring too?

**Comment by ericgio** [comment]
Yes, if *any* of the text is highlighted because it matches the text in the input, then the bug repros. If there are no highlighted characters, it works fine.

**Comment by alexgurr** [comment]
Ahhh now I understand what you mean by highlighted characters - the bold highlights that match the input content. OK, we're on the same page. Seems to be the same issue then.

On 5 Sep 2017, 20:28 +0100, Eric Giovanola <notifications@github.com>, wrote:

Yes, if any of the text is highlighted because it matches the text in the input, then the bug repros. If there are no highlighted characters, it works fine.

**Comment by jasonmullins** [comment]
@ericgio is talking about the part of the text that is enclosed in a span with a class that makes it bold (the part that matches the search text).  I think there is some confusion regarding highlighting the text by selecting it with the mouse, etc, verses the span that gets marked as "highlighted" or "matches".

**Comment by tintin64** [comment]
Looks like its fixed on your demo page, any ETA on releasing this fix?

**Comment by ericgio** [comment]
The main demo page is v1.4, but the issue in question is a regression in v2.0. I don't have a fix yet, unfortunately.

**Comment by tomislavhren** [comment]
@ericgio 
I found out that if you put `pointer-events: none;` on `<strong>some highlighted text in menu</strong>` it works that, you can click on both highlighted text or anywhere within that link

**Comment by ericgio** [comment]
@tomislavhren: Thanks for the tip! Will try to publish a fix as soon as I can.

**Comment by Gulivertx** [comment]
Is there any workaround until a fix will be deployed ? thank you for your answer.

**Comment by ericgio** [comment]
This is now fixed in v2.0.0-alpha.4. Apologies for the delay.

**Comment by Gulivertx** [comment]
Still not, maybe it is not the same trouble ....
When I click on a text in a select it's not working, if I click just next to the text the selection is OK.

**Comment by ericgio** [comment]
@Gulivertx: I don't know what your issue is. The issue referenced on this thread should be fixed if you update to the latest version. If you're still seeing an issue, can you please open another ticket with specific repro steps? Thanks.

**Comment by sorahn** [comment]
@ericgio I'm also still seeing this issue on .v4.  I only have a very basic component `<Typeahead options={options} />`

Repro:
1. Type something so there are matches (don't press enter or arrow keys or anything).
2. Click on the word for one of matches. - Nothing happens. (Occasionally flashes the selected color on the row)
3. Click next to the same word. - Selects that item and menu closes.


The same thing seems to happen if you've pressed the 'down' arrow to select one of the items.  They just don't seem to respond to clicking on the text itself.

**Comment by ericgio** [comment]
> I didn't realize that the fix for the highlighter was in the CSS. Confirmed as fixed over here! Sorry for the false alarm.

Yup. Glad it's working for you.

**Comment by Gulivertx** [comment]
Yes sorry, after importing your last CSS code everything works fine ! Thank you for the fix

**Comment by ericgio** [comment]
Just for posterity, this issue was potentially related to: https://github.com/helior/react-highlighter/issues/20
