### ISSUE TITLE
[React 16.2] Warning: Component Menu declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

### ISSUE THREAD

**Issue by AlvinStanescu** [ericgio/react-bootstrap-typeahead#274]
### Version
2.0.1

### Steps to reproduce

1. Install React 16.2, as it only repros with the latest version.
2. In Chrome (or probably any other browser), open the dev console.
3. Take any Typeahead instance you might have, and type enough characters to show the menu.

### Expected Behavior
1. No warnings/errors.

### Actual Behavior
As soon as the menu pops up, React shows the following:
`Warning: Component Menu declared ``PropTypes`` instead of ``propTypes``. Did you misspell the property assignment?`

**Comment by ericgio** [comment]
Nice catch, thanks!

**Comment by ericgio** [comment]
Fixed in v2.0.2

**Comment by AlvinStanescu** [comment]
Great, thanks for the quick fix! 👍

**Comment by ToJen** [comment]
Looks like this issue still exists:

`Warning: Component FieldWrapper declared ``PropTypes`` instead of ``propTypes``. Did you misspell the property assignment?`

**Comment by ericgio** [comment]
@ToJen: `FieldWrapper` isn't part of this package. The error you're seeing is coming from somewhere else.

**Comment by illiteratewriter** [comment]
@ToJen The error you're seeing might be because you did something like 
`FieldWrapper.PropTypes = {
  foo: PropTypes.string.isRequired
}`

the first `PropTypes` is supposed to be a small letter. It should be 
`FieldWrapper.propTypes = {
  foo: PropTypes.string.isRequired
}`

**Comment by ToJen** [comment]
@illiteratewriter @ericgio  I think my errors are either coming from `react-native-clean-form` or `redux-form`.

**Comment by xiaochuankk123** [comment]
@illiteratewriter  thanks,bro. It resolve my problem.

**Comment by jorgeoxi** [comment]
Thanks man!

**Comment by BrianFarias** [comment]
FieldWrapper.--->p<---ropTypes = {
  foo: PropTypes.string.isRequired
}

I learned something new today

**Comment by yuehui123** [comment]
把PropTypes改成propTypes

**Comment by jamessv** [comment]
Try to use this way

NumberFields.**propTypes** = {
    value: **PropTypes**.number.isRequired,
    onChange: PropTypes.func.isRequired,
    name: PropTypes.string.isRequired
}
